# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Oct  8 22:44:24 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.10.8
source:
  sha256: 78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872
  url: https://pypi.io/packages/source/c/certifi/certifi-2021.10.8.tar.gz
build:
  number: '0'
  string: h5b45459_0
requirements:
  build: []
  run: []
test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
    - curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
